# add this repository to:
# https://github.com/users/${username}/packages/container/#{repo}/settings

# https://qiita.com/fudekun/items/0dad3f2251cca992d7d4
# https://takuya-1st.hatenablog.jp/entry/2021/09/27/134200

name: build and push container image 

# 1. Trigger
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    # 2. setup variables
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y%m%d')"

   # 3. Checkout code
    - name: Checkout
      uses: actions/checkout@v2
 
   # 4. Login to Github Container Registry
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

   # 5. setup buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 6. Build and Push
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        # 7. nameing
        tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.CI_REPOSITORY_NAME }}:${{ steps.date.outputs.today }}
            ghcr.io/${{ github.repository_owner }}/${{ env.CI_REPOSITORY_NAME }}:latest
